# Generated by Django 5.1.3 on 2024-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_contenido', '0003_alter_terminospareados_uso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapas',
            old_name='habilidad',
            new_name='habilidad_matematica',
        ),
        migrations.AddField(
            model_name='etapas',
            name='habilidad_bloom',
            field=models.TextField(choices=[('Conocer', 'Conocer'), ('Comprender', 'Comprender'), ('Aplicar', 'Aplicar'), ('Analizar', 'Analizar'), ('Evaluar', 'Evaluar'), ('Crear', 'Crear')], default='Conocer', max_length=50),
            preserve_default=False,
        ),
    ]
