# Generated by Django 5.1.3 on 2024-12-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_contenido', '0004_rename_habilidad_etapas_habilidad_matematica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapas',
            name='contenido_abordado',
            field=models.TextField(default='Espacio Muestral'),
            preserve_default=False,
        ),
    ]
