# Generated by Django 5.1.3 on 2024-12-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_contenido', '0005_etapas_contenido_abordado'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapas',
            name='es_ultima',
            field=models.BooleanField(default=False),
        ),
    ]
