# Generated by Django 5.1.3 on 2024-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_contenido', '0006_etapas_es_ultima'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=255),
            preserve_default=False,
        ),
    ]
