# Generated by Django 5.1.3 on 2024-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_contenido', '0007_niveles_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='habilidad_bloom',
            field=models.TextField(choices=[('Recordar', 'Recordar'), ('Comprender', 'Comprender'), ('Aplicar', 'Aplicar'), ('Analizar', 'Analizar'), ('Evaluar', 'Evaluar'), ('Crear', 'Crear')], max_length=50),
        ),
    ]
