# Generated by Django 5.1.3 on 2024-11-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OA',
            fields=[
                ('id_OA', models.AutoField(primary_key=True, serialize=False)),
                ('OA', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaProbabilidad',
            fields=[
                ('id_problema', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('enunciado', models.TextField()),
                ('espacio_muestral', models.TextField()),
                ('elementos_evento', models.TextField()),
                ('numerador', models.IntegerField()),
                ('denominador', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminosPareados',
            fields=[
                ('id_termino', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('definicion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id_nivel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('OA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattrix_contenido.oa')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresEvaluacion',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('id_OA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattrix_contenido.oa')),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('componente', models.TextField()),
                ('dificultad', models.TextField()),
                ('habilidad', models.TextField()),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
                ('id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattrix_contenido.niveles')),
                ('OA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattrix_contenido.oa')),
            ],
        ),
    ]
