# Generated by Django 5.1.3 on 2024-11-30 18:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'ciudad'), name='nombre_unico_ciudad')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalColegio',
            fields=[
                ('id_colegio', models.BigIntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Colegio',
                'verbose_name_plural': 'historical Colegios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('7° Básico', '7° Básico'), ('8° Básico', '8° Básico'), ('1° Medio', '1° Medio'), ('2° Medio', '2° Medio'), ('3° Medio', '3° Medio'), ('4° Medio', '4° Medio')], max_length=50)),
                ('letra', models.CharField(max_length=1)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='mattrix_admin.colegio')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'constraints': [models.UniqueConstraint(fields=('nivel', 'letra', 'colegio'), name='unique_curso')],
            },
        ),
    ]
