# Generated by Django 5.1.3 on 2024-11-30 18:07

import django.db.models.deletion
import mattrix_usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mattrix_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=mattrix_usuarios.models.obtener_ruta_imagen)),
                ('uso', models.CharField(choices=[('avatar', 'Avatar'), ('fondo-nivel', 'Fondo Nivel')], default='avatar', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('admin', 'Administrador')], default='student', max_length=20)),
                ('pais', models.CharField(choices=[('Chile', 'Chile'), ('Venezuela', 'Venezuela'), ('Colombia', 'Colombia'), ('Perú', 'Perú')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('avatarUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mattrix_usuarios.imagenes')),
                ('colegio', models.ForeignKey(blank=True, help_text='Aplicable si el usuario es estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='mattrix_admin.colegio')),
                ('curso', models.ForeignKey(blank=True, help_text='Aplicable si el usuario es estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='mattrix_admin.cursos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['rol', 'curso__nivel', 'curso__letra', 'user__username'],
            },
        ),
    ]
