# Generated by Django 5.1.3 on 2024-12-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_docentes', '0004_remove_avanceestudiantes_cantidad_intentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaescrita',
            old_name='id_avance',
            new_name='avance',
        ),
        migrations.RemoveField(
            model_name='respuestaescrita',
            name='respuesta1',
        ),
        migrations.RemoveField(
            model_name='respuestaescrita',
            name='respuesta2',
        ),
        migrations.RemoveField(
            model_name='respuestaescrita',
            name='respuesta3',
        ),
        migrations.AddField(
            model_name='respuestaescrita',
            name='pregunta',
            field=models.TextField(default=1, help_text='Pregunta asociada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaescrita',
            name='respuesta',
            field=models.TextField(default='1', help_text='Respuesta del estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaescrita',
            name='retroalimentacion',
            field=models.TextField(blank=True, help_text='Retroalimentación para la respuesta', null=True),
        ),
    ]
