# Generated by Django 5.1.3 on 2024-11-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mattrix_contenido', '0001_initial'),
        ('mattrix_usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceEstudiantes',
            fields=[
                ('id_avance', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo', models.CharField(help_text='Tiempo invertido en la etapa', max_length=8)),
                ('cantidad_intentos', models.IntegerField()),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('logro', models.PositiveIntegerField(help_text='Porcentaje de logro alcanzado en la etapa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='mattrix_contenido.etapas')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='docente_relaciones', to='mattrix_usuarios.profile')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_relaciones', to='mattrix_usuarios.profile')),
            ],
            options={
                'verbose_name': 'Relación Docente-Estudiante',
                'verbose_name_plural': 'Relaciones Docente-Estudiantes',
                'unique_together': {('docente', 'estudiante')},
            },
        ),
    ]
