# Generated by Django 5.1.3 on 2024-12-01 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docenteestudiante',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
