# Generated by Django 5.1.3 on 2024-12-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_docentes', '0003_respuestaescrita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avanceestudiantes',
            name='cantidad_intentos',
        ),
    ]
