# Generated by Django 5.1.3 on 2024-12-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_admin', '0001_initial'),
        ('mattrix_usuarios', '0004_alter_profile_avataruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colegio',
            field=models.ForeignKey(default='1', help_text='Aplicable si el usuario es estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='mattrix_admin.colegio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='curso',
            field=models.ForeignKey(default='1', help_text='Aplicable si el usuario es estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='mattrix_admin.cursos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
