# Generated by Django 5.1.3 on 2024-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattrix_usuarios', '0006_alter_profile_avataruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='uso',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('avatarDocente', 'AvatarDocente'), ('fondo-nivel', 'Fondo Nivel')], default='avatar', max_length=20),
        ),
    ]
